using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using GoogleAnalyticsLinqProvider.Core;

namespace GoogleAnalyticsLinqProvider.Parsers
{
    /// <summary>
    /// Povides the data generated by parser of Lambda Expression in 'Select' clause.
    /// </summary>
    internal class SelectExpressionParserResult
    {
        /// <summary>
        /// The set of dimendions
        /// </summary>
        public List<string> Dimensions { get; set; }

        /// <summary>
        /// The set of metrics
        /// </summary>
        public List<string> Metrics { get; set; }

        /// <summary>
        /// The map of ContextModel fields and result object fields
        /// </summary>
        public FieldsMap FieldsMap { get; set; }
    }
}
